name: Pruebas E2E con Cypress

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/stepup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-actions@v6
        with:
         browser: chrome

         command: npx cypress run